/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppMetasRouteImport } from './routes/_app.metas'
import { Route as AppLancamentosRouteImport } from './routes/_app.lancamentos'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConsultorIaRouteImport } from './routes/_app.consultor-ia'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppAdminLojasRouteImport } from './routes/_app.admin.lojas'
import { Route as AppAdminConfiguracoesRouteImport } from './routes/_app.admin.configuracoes'
import { Route as AppAdminAssinaturasRouteImport } from './routes/_app.admin.assinaturas'
import { Route as AppAdminAlertasRouteImport } from './routes/_app.admin.alertas'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppLancamentosRoute = AppLancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultorIaRoute = AppConsultorIaRouteImport.update({
  id: '/consultor-ia',
  path: '/consultor-ia',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLojasRoute = AppAdminLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminConfiguracoesRoute = AppAdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAssinaturasRoute = AppAdminAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAlertasRoute = AppAdminAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/configuracoes': typeof AppConfiguracoesRoute
  '/consultor-ia': typeof AppConsultorIaRoute
  '/dashboard': typeof AppDashboardRoute
  '/lancamentos': typeof AppLancamentosRoute
  '/metas': typeof AppMetasRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/admin/alertas': typeof AppAdminAlertasRoute
  '/admin/assinaturas': typeof AppAdminAssinaturasRoute
  '/admin/configuracoes': typeof AppAdminConfiguracoesRoute
  '/admin/lojas': typeof AppAdminLojasRoute
  '/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/consultor-ia': typeof AppConsultorIaRoute
  '/dashboard': typeof AppDashboardRoute
  '/lancamentos': typeof AppLancamentosRoute
  '/metas': typeof AppMetasRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/admin/alertas': typeof AppAdminAlertasRoute
  '/admin/assinaturas': typeof AppAdminAssinaturasRoute
  '/admin/configuracoes': typeof AppAdminConfiguracoesRoute
  '/admin/lojas': typeof AppAdminLojasRoute
  '/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/consultor-ia': typeof AppConsultorIaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/lancamentos': typeof AppLancamentosRoute
  '/_app/metas': typeof AppMetasRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/admin/alertas': typeof AppAdminAlertasRoute
  '/_app/admin/assinaturas': typeof AppAdminAssinaturasRoute
  '/_app/admin/configuracoes': typeof AppAdminConfiguracoesRoute
  '/_app/admin/lojas': typeof AppAdminLojasRoute
  '/_app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/configuracoes'
    | '/consultor-ia'
    | '/dashboard'
    | '/lancamentos'
    | '/metas'
    | '/relatorios'
    | '/admin/alertas'
    | '/admin/assinaturas'
    | '/admin/configuracoes'
    | '/admin/lojas'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/consultor-ia'
    | '/dashboard'
    | '/lancamentos'
    | '/metas'
    | '/relatorios'
    | '/admin/alertas'
    | '/admin/assinaturas'
    | '/admin/configuracoes'
    | '/admin/lojas'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/configuracoes'
    | '/_app/consultor-ia'
    | '/_app/dashboard'
    | '/_app/lancamentos'
    | '/_app/metas'
    | '/_app/relatorios'
    | '/_app/admin/alertas'
    | '/_app/admin/assinaturas'
    | '/_app/admin/configuracoes'
    | '/_app/admin/lojas'
    | '/_app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metas': {
      id: '/_app/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lancamentos': {
      id: '/_app/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof AppLancamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultor-ia': {
      id: '/_app/consultor-ia'
      path: '/consultor-ia'
      fullPath: '/consultor-ia'
      preLoaderRoute: typeof AppConsultorIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/lojas': {
      id: '/_app/admin/lojas'
      path: '/lojas'
      fullPath: '/admin/lojas'
      preLoaderRoute: typeof AppAdminLojasRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/configuracoes': {
      id: '/_app/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AppAdminConfiguracoesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/assinaturas': {
      id: '/_app/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AppAdminAssinaturasRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/alertas': {
      id: '/_app/admin/alertas'
      path: '/alertas'
      fullPath: '/admin/alertas'
      preLoaderRoute: typeof AppAdminAlertasRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAlertasRoute: typeof AppAdminAlertasRoute
  AppAdminAssinaturasRoute: typeof AppAdminAssinaturasRoute
  AppAdminConfiguracoesRoute: typeof AppAdminConfiguracoesRoute
  AppAdminLojasRoute: typeof AppAdminLojasRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAlertasRoute: AppAdminAlertasRoute,
  AppAdminAssinaturasRoute: AppAdminAssinaturasRoute,
  AppAdminConfiguracoesRoute: AppAdminConfiguracoesRoute,
  AppAdminLojasRoute: AppAdminLojasRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppConsultorIaRoute: typeof AppConsultorIaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLancamentosRoute: typeof AppLancamentosRoute
  AppMetasRoute: typeof AppMetasRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppConsultorIaRoute: AppConsultorIaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLancamentosRoute: AppLancamentosRoute,
  AppMetasRoute: AppMetasRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
